apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: catalog-bootstrap
spec:
  targets:
    - ./entities.yaml
    - ./org.yaml
    - ../templates/repo-template/template.yaml
    - ../templates/csharp-repo-template/template.yaml
